name: Build and Test

# Run this workflows every time a new commit pushed to your repository
on: push

jobs:
  build-and-test:
    # Name the Job
    name: Build and Test the Compiler
    # Set the type of machine to run on
    runs-on: ubuntu-latest

    steps:
      # Checks out a copy of your repository on the ubuntu-latest machine
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Install llvm repository
        run: wget https://apt.llvm.org/llvm.sh && chmod +x llvm.sh && sudo ./llvm.sh 11

      - name: Install dependcies
        run: sudo apt-get update && sudo apt-get install -y cmake ninja-build clang-tools-11 clang-11-doc libclang-11-dev libfuzzer-11-dev

      - name: Build and Test
        run: CC=/usr/bin/clang-11 CXX=/usr/bin/clang++-11 make all
